name: Ansible Test
'on':
  pull_request_target:
    types:
    - opened
    - synchronize
  push:
    branches:
    - main
    - stable-*
concurrency:
  group: "${{ github.workflow }}-${{\n  github.event.pull_request.number || github.sha\n\
    }}"
  cancel-in-progress: true
jobs:
  integration:
    runs-on: ubuntu-latest
    environment: eco-mecm
    name: "I (\u24B6${{ matrix.ansible }}"
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
        - ansible: devel
          python: 3.12
        - ansible: stable-2.16
          python: 3.11
        - ansible: stable-2.17
          python: 3.11
        - ansible: stable-2.18
          python: 3.11
        - ansible: stable-2.19
          python: 3.11
    steps:
    - name: Install python
      run: "set -euxo pipefail\nif ! command -v python${{ matrix.python }}; then\n\
        \  sudo dnf install -y \\\n    python${{ matrix.python }} \\\n    python${{\
        \ matrix.python }}-pip\nfi\n"
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Run integration tests
      run: 'python${{ matrix.python }} -m venv .venv

        source .venv/bin/activate

        pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible
        }}.tar.gz

        make integration ANSIBLE_COLLECTIONS_PATH="${{ github.workspace }}"

        '
      env:
        ANSIBLE_COLLECTIONS_PATH: ${{ github.workspace }}
        MECM_HOSTNAME: ${{ secrets.MECM_HOSTNAME }}
        MECM_USERNAME: ${{ secrets.MECM_USERNAME }}
        MECM_PASSWORD: ${{ secrets.MECM_PASSWORD }}
    - name: Clean up
      if: always()
      run: 'rm -rf ./*

        '
  check:
    if: always()
    needs:
    - integration
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
